# Site settings
title: Trever Santora - UX Designer
email: santora.t@gmail.com
description: ""
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty

include: [
  ".htaccess"
  ]
exclude: [
  "*.git",
  "*.gitignore",
  "CNAME",
  "*.scss-cache",
  "readme.md",
  "node_modules",
  "gruntfile.js",
  "package.json",
  "bower_components",
  "bower.json",
  "feed.xml",
  "js/capture.js",
  "js/app.js",
  "js/jquery.validate.js",
  "js/additional-methods.js",
  "js/validation-rules.js"
  ]
prose:
  rooturl: '_posts'
  siteurl: 'http://trever-s.github.io'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "hidden"
          value: ""
      - name: "date"
        field:
            element: "text"
            label: "Date (YYYY-MM-DD)"
            value: ""
      - name: "author"
        field:
            element: "text"
            label: "Please enter the author's name."
            value: ""
      - name: "excerpt"
        field:
            element: "text"
            label: "Give a brief description of your blog post."
            value: ""
